# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WC
tagline:          'Blog for posting'
url:              http://woogui.github.io
baseurl:          /

author:
  name:           'Woo Cheol Jung'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
